### ISSUE TITLE
Provide details on how to install on Windows

### ISSUE THREAD

**Issue by leggetter** [tigrisdata/tigris-cli#210]
The CLI builds for Windows, but it's not clear if the binary is distributed in the same way as it is for Mac and Linux.

Suggestion:

1. Check/update the build to ensure a Windows binary is built and distributed
2. Update the installation docs (README and https://www.tigrisdata.com/docs/sdkstools/cli/installation/) to provide instructions for Windows

**Comment by ovaistariq** [comment]
@efirs if this is something quick, could you look into it.

**Comment by leggetter** [comment]
Happy to do the docs and help with some testing.

**Comment by efirs** [comment]
I've crated #223 to simplify installation on Windows.

But we always were publishing a binary for Windows https://github.com/tigrisdata/tigris-cli/releases/tag/v1.0.0-beta.22
Not sure what would be Windows idiomatic installation instructions.

Also would npm -i -g @tigrisdata/tigris-cli
work on Windows?

**Comment by ovaistariq** [comment]
Yes the npm command should work on windows as well

**Comment by leggetter** [comment]
https://github.com/tigrisdata/tigris-docs/pull/396 adds NPM install instructions. We can merge that anyway, but we know it won't currently work for Windows.

**Comment by leggetter** [comment]
The zip file is uploaded (e.g. https://github.com/tigrisdata/tigris-cli/releases/download/v1.0.0-beta.28/tigris_1.0.0-beta.28_windows_amd64.zip) so the problem seems to be with the installation process
