### ISSUE TITLE
Should url in config file affect the port mapping?

### ISSUE THREAD

**Issue by VetchM** [tigrisdata/tigris-cli#280]
I'm following the offical doc to start a local server, and find that changing the port of `url` in config file will not affect the port mapping, which is always 8081:8081, unless set in command line.

```sh
~/tigris❯ tigris config show
url: 0.0.0.0:11111
timeout: 5s
protocol: grpc

~/tigris❯ tigris dev start
latest: Pulling from tigrisdata/tigris-local
Digest: sha256:f73d5909932fa16d7788a53740cee30711a845c08c1a52959438c3a36cabc6d5
Status: Image is up to date for tigrisdata/tigris-local:latest
Tigris is running at localhost:8081

~/tigris❯ tigris dev start 11111
latest: Pulling from tigrisdata/tigris-local
Digest: sha256:f73d5909932fa16d7788a53740cee30711a845c08c1a52959438c3a36cabc6d5
Status: Image is up to date for tigrisdata/tigris-local:latest
Tigris is running at localhost:11111
run 'export TIGRIS_URL=localhost:11111' for tigris cli to connect to the local instance
```

Is this the excepted behavior? If not, maybe i can fix this. 
<https://github.com/tigrisdata/tigris-cli/blob/8ee9c213e499e801418ebb69c0e0cea5eb7f312c/cmd/local.go#L195>
Btw the default name for config file in code is `tigris-cli`, but in the doc is still `tigris`, which one shoud be fixed?

**Comment by efirs** [comment]
Hi, @VetchM !
Thanks for your interest in contributing.
This looks like legitimate issue.
