### ISSUE TITLE
Error connecting to the docker container  

### ISSUE THREAD

**Issue by seeforschauer** [tigrisdata/tigris-cli#46]
Steps to reproduce:
1. create a docker-compose file where TigrisDB container is used
2. Run `tigris list databases` gives error `unknown service tigrisdata.v1.Tigris`
3. Attempt to connect from tigris golang client gives error `[driver.go:40 tigris.NewConn] cannot connect to localhost:8081: write tcp 127.0.0.1:49086->127.0.0.1:8081: write: broken pipe` 
4. `tigris local logs -f` output is `Error: No such container: tigris-local-server`
5. `docker ps` output is
```
docker ps 
CONTAINER ID   IMAGE                              COMMAND                  CREATED              STATUS              PORTS                        NAMES
e6f6cb891633   tigrisdata/tigrisdb:latest         "bash -c 'fdbcli --e…"   About a minute ago   Up About a minute   127.0.0.1:8081->8081/tcp     tigrisdb
f310a71952d7   mongo:5.0.7                        "docker-entrypoint.s…"   About a minute ago   Up About a minute   127.0.0.1:37017->27017/tcp   mongodb
4b16a920050b   foundationdb/foundationdb:6.3.23   "/usr/bin/tini -g --…"   About a minute ago   Up About a minute   127.0.0.1:4500->4500/tcp     tigrisdb_fdb
```

* Docker Tigris version
```
docker pull tigrisdata/tigrisdb:latest
latest: Pulling from tigrisdata/tigrisdb
Digest: sha256:275af0990bfd0048746ba94cfb6406122d3029c8e904cd39d33594c908d8ac30
Status: Image is up to date for tigrisdata/tigrisdb:latest
docker.io/tigrisdata/tigrisdb:latest
```
* tigris cli version v1.0.0-alpha.8

* golang cli version is `github.com/tigrisdata/tigris-client-go v1.0.0-alpha.10`

**Comment by ovaistariq** [comment]
Using the correct Docker image fixed the issue. I have deleted the older Docker image repo.
